// 66 books catalog for quick browsing; slugs match bible-api.com
export const BOOKS = [
  { name: 'Gênesis', slug: 'genesis', chapters: 50 },
  { name: 'Êxodo', slug: 'exodus', chapters: 40 },
  { name: 'Levítico', slug: 'leviticus', chapters: 27 },
  { name: 'Números', slug: 'numbers', chapters: 36 },
  { name: 'Deuteronômio', slug: 'deuteronomy', chapters: 34 },
  { name: 'Josué', slug: 'joshua', chapters: 24 },
  { name: 'Juízes', slug: 'judges', chapters: 21 },
  { name: 'Rute', slug: 'ruth', chapters: 4 },
  { name: '1 Samuel', slug: '1%20samuel', chapters: 31 },
  { name: '2 Samuel', slug: '2%20samuel', chapters: 24 },
  { name: '1 Reis', slug: '1%20kings', chapters: 22 },
  { name: '2 Reis', slug: '2%20kings', chapters: 25 },
  { name: '1 Crônicas', slug: '1%20chronicles', chapters: 29 },
  { name: '2 Crônicas', slug: '2%20chronicles', chapters: 36 },
  { name: 'Esdras', slug: 'ezra', chapters: 10 },
  { name: 'Neemias', slug: 'nehemiah', chapters: 13 },
  { name: 'Ester', slug: 'esther', chapters: 10 },
  { name: 'Jó', slug: 'job', chapters: 42 },
  { name: 'Salmos', slug: 'psalms', chapters: 150 },
  { name: 'Provérbios', slug: 'proverbs', chapters: 31 },
  { name: 'Eclesiastes', slug: 'ecclesiastes', chapters: 12 },
  { name: 'Cantares', slug: 'song%20of%20solomon', chapters: 8 },
  { name: 'Isaías', slug: 'isaiah', chapters: 66 },
  { name: 'Jeremias', slug: 'jeremiah', chapters: 52 },
  { name: 'Lamentações', slug: 'lamentations', chapters: 5 },
  { name: 'Ezequiel', slug: 'ezekiel', chapters: 48 },
  { name: 'Daniel', slug: 'daniel', chapters: 12 },
  { name: 'Oséias', slug: 'hosea', chapters: 14 },
  { name: 'Joel', slug: 'joel', chapters: 3 },
  { name: 'Amós', slug: 'amos', chapters: 9 },
  { name: 'Obadias', slug: 'obadiah', chapters: 1 },
  { name: 'Jonas', slug: 'jonah', chapters: 4 },
  { name: 'Miquéias', slug: 'micah', chapters: 7 },
  { name: 'Naum', slug: 'nahum', chapters: 3 },
  { name: 'Habacuque', slug: 'habakkuk', chapters: 3 },
  { name: 'Sofonias', slug: 'zephaniah', chapters: 3 },
  { name: 'Ageu', slug: 'haggai', chapters: 2 },
  { name: 'Zacarias', slug: 'zechariah', chapters: 14 },
  { name: 'Malaquias', slug: 'malachi', chapters: 4 },
  { name: 'Mateus', slug: 'matthew', chapters: 28 },
  { name: 'Marcos', slug: 'mark', chapters: 16 },
  { name: 'Lucas', slug: 'luke', chapters: 24 },
  { name: 'João', slug: 'john', chapters: 21 },
  { name: 'Atos', slug: 'acts', chapters: 28 },
  { name: 'Romanos', slug: 'romans', chapters: 16 },
  { name: '1 Coríntios', slug: '1%20corinthians', chapters: 16 },
  { name: '2 Coríntios', slug: '2%20corinthians', chapters: 13 },
  { name: 'Gálatas', slug: 'galatians', chapters: 6 },
  { name: 'Efésios', slug: 'ephesians', chapters: 6 },
  { name: 'Filipenses', slug: 'philippians', chapters: 4 },
  { name: 'Colossenses', slug: 'colossians', chapters: 4 },
  { name: '1 Tessalonicenses', slug: '1%20thessalonians', chapters: 5 },
  { name: '2 Tessalonicenses', slug: '2%20thessalonians', chapters: 3 },
  { name: '1 Timóteo', slug: '1%20timothy', chapters: 6 },
  { name: '2 Timóteo', slug: '2%20timothy', chapters: 4 },
  { name: 'Tito', slug: 'titus', chapters: 3 },
  { name: 'Filemom', slug: 'philemon', chapters: 1 },
  { name: 'Hebreus', slug: 'hebrews', chapters: 13 },
  { name: 'Tiago', slug: 'james', chapters: 5 },
  { name: '1 Pedro', slug: '1%20peter', chapters: 5 },
  { name: '2 Pedro', slug: '2%20peter', chapters: 3 },
  { name: '1 João', slug: '1%20john', chapters: 5 },
  { name: '2 João', slug: '2%20john', chapters: 1 },
  { name: '3 João', slug: '3%20john', chapters: 1 },
  { name: 'Judas', slug: 'jude', chapters: 1 },
  { name: 'Apocalipse', slug: 'revelation', chapters: 22 },
];


